### ISSUE TITLE
Implicit dependency on velodyne_pointcloud package

### ISSUE THREAD

**Issue by dwisth** [ori-drs/lidar_undistortion#18]
When @mcamurri and I did some testing on ANYmal on Friday we noticed that vilens didn't work with the `/velodyne_packets` topic. It did previously before the upgrade.

At the time we thought that this didn't work since ANYbotics have defined their own custom Velodyne ros message type, `any_velodyne_msgs`, which defined exactly the same as the standard `velodyne_msgs`.  To test this I made a small conversion node between the two message types (pushed to `feature/anybotics-to-standard-velo-msg-converter` branch of `anymal_logging_drs`). However, this wasn't the problem and vilens could subscribe to both message types correctly - probably because they are defined exactly the same.

After further investigation, it failed because we didn't have the `velodyne_pointcloud` package installed by default. The `VelodyneScanConverter` implicitly relies on this package if the [rosparams do not point to a particular calibration file](https://github.com/ori-drs/lidar_undistortion/blob/2a0d0b0f39e81d8cfc3511b318ee6ef3eba6a23f/lidar_undistortion_ros/include/lidar_undistortion_ros/velodyne_scan_converter.hpp#L58). Therefore the scan converter wasn't able to load its parameters and didn't convert any points.

@mcamurri - what do you think is the best way to resolve this? Maybe make it point to a calibration file in `lidar_undistortion_ros` and fail if it can't find one?

**Comment by wxmerkt** [comment]
This might be due to an undeclared transient dependency, cf. the CMakeLists which tries to link against a variable that is never find_package'd:
https://github.com/ori-drs/lidar_undistortion/blob/2a0d0b0f39e81d8cfc3511b318ee6ef3eba6a23f/lidar_undistortion/CMakeLists.txt#L54

And it's also not included in the related package.xml: https://github.com/ori-drs/lidar_undistortion/blob/2a0d0b0f39e81d8cfc3511b318ee6ef3eba6a23f/lidar_undistortion/package.xml#L14-L16

Fixing the package.xml/CMakeLists likely resolves this. I also noticed a warning pop up about "xxx not found, not building velodyne" when compiling. This might be related. The warning is here:
https://github.com/ori-drs/lidar_undistortion/blob/2a0d0b0f39e81d8cfc3511b318ee6ef3eba6a23f/lidar_undistortion_ros/CMakeLists.txt#L22-L32

It's possible you didn't notice the warning due to tons of other warnings from other packages

**Comment by mcamurri** [comment]
That was an attempt to have an optional compilation of the velodyne undistortion part. I think it was working on melodic, but anyway ROS does not support "optional" packages. 

Let's make this mandatory and move on. I will make a pull request.

**Comment by dwisth** [comment]
Okay, sounds good. We will probably need to add it to the list of packages to install by default in `drs_base` too.

Do we need the whole `velodyne_pointcloud` package or just the one config file?

**Comment by mcamurri** [comment]
I turns out there was no need to depend on `velodyne_pointcloud`. Basically what happened is the following:

1. I wanted `lidar_undistortion` to depend on code on velodyne that wasn't ROS dependent, but it wasn't possible because the velodyne package does not separate ROS from non-ROS code. 
2. I therefore copied and de-ROS-fied the code into `lidar_undistortion`
3. I have left a header file that was conflicting with the local version

Check this branch that [fixes all of these things](https://github.com/ori-drs/lidar_undistortion/pull/17).
